### ISSUE TITLE
Panic on sFlow from OpenVSwitch

### ISSUE THREAD

**Issue by alexanderturner** [Cistern/cistern#62]
Trying to enable sFlow from OVS with config:
`ovs-vsctl   --   --id=@s create sFlow agent=enp0s8  target=\"127.0.0.1:6343\" header=128 sampling=64 polling=10  -- set Bridge testbr sflow=@s`

This is the output from Cistern:
```

root@ubuntu:~# ./cistern
2017/01/04 17:27:04 main.go:54: Cistern version 0.0.4 starting
2017/01/04 17:27:04 clock.go:13:   Starting internal clock
2017/01/04 17:27:04 main.go:57:   Attempting to load configuration file at /opt/cistern/config.json
2017/01/04 17:27:04 main.go:60: ✗ Could not load configuration: `open /opt/cistern/config.json: no such file or directory`
2017/01/04 17:27:04 main.go:71: ✓ Successfully loaded configuration
2017/01/04 17:27:04 service.go:54: listening for sFlow datagrams on :6343
2017/01/04 17:27:04 service.go:59: listening for AppFlow datagrams on :6344
2017/01/04 17:27:04 main.go:90: ✓ Successfully started network service
2017/01/04 17:27:09 service.go:73: 10.0.3.15 is unknown. Registering new source.
2017/01/04 17:27:09 service.go:82: Source{10.0.3.15} needs class "sflow".
2017/01/04 17:27:09 source.go:34: registering class sflow for Source{10.0.3.15}
2017/01/04 17:27:09 source.go:66:   Source{10.0.3.15} does not have class "switch-counters" registered
2017/01/04 17:27:09 source.go:34: registering class switch-counters for Source{10.0.3.15}
2017/01/04 17:27:09 source.go:66:   Source{10.0.3.15} does not have class "metrics" registered
2017/01/04 17:27:09 source.go:34: registering class metrics for Source{10.0.3.15}
2017/01/04 17:27:09 engine.go:51: [Series engine] Writing 14 observations
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a98de]

goroutine 1 [running]:
panic(0x7b6180, 0xc82000a0f0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/Cistern/cistern/state/series.(*Engine).writeObservations(0x0, 0xc8200da000, 0xe, 0x10)
	/Users/alexanderturner/Code/gocode/src/github.com/Cistern/cistern/state/series/engine.go:52 +0xde
github.com/Cistern/cistern/state/series.(*Engine).Process(0x0, 0xc820016a80)
	/Users/alexanderturner/Code/gocode/src/github.com/Cistern/cistern/state/series/engine.go:47 +0xae
main.main()
	/Users/alexanderturner/Code/gocode/src/github.com/Cistern/cistern/main.go:96 +0x1094
```

**Comment by Preetam** [comment]
Ouch. I'll take a look later today!

**Comment by alexanderturner** [comment]
Perfect! Thanks! Where's the documentation hiding (if any)

**Comment by Preetam** [comment]
Unfortunately there isn't any documentation. I've basically left this project in a partially completed state, and haven't done anything substantial in a while. What are you trying to do / use it for?

**Comment by alexanderturner** [comment]
Ah ok, wanting to get flow stats from OVS then sort by top talkers and interface for another application im working on
